Home work#9
sergkonhar/Home-works-C-R_D pull request #4
Opened 2023-11-30 23:37 UTC by sergkonhar

@bohdanpc, @helen-black, проверьте пожалуйста домашнее задание #9

2023-12-11 19:33 UTC, helen-black requested changes

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +			inputChar[i] = inputChar[i];
do you need it?

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +		if (isalpha(inputChar[i])) {
read about isalpha(). do you need this check?

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +	std::cout << "Result string: " << inputChar;
functions  shouldn't speak

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +			std::cout << inputNum[i] << " ";
the same

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +			continue;
you don't need **continue** here

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +	for (int i = 0; i < strlen(palindromeArray); i++) {
you can create variable to store strlen(palindromeArray). and use it here and inside of the loop

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +	for (int i = 0; i < strlen(palindromeArray); i++) {
do you need to check the whole string?

2023-12-11 19:33 UTC, helen-black commented on HW#9/Functions.cpp
> +
you can refactor it:
```c++
if (strlen(firstString) != strlen(secondString)) {
    return false;
}
for (int i = 0; i < strlen(firstString); i++) {
    if (firstString[i] != secondString[i]) {
          return false;
    }
}
return true;
```

2023-12-11 19:33 UTC, helen-black commented on HW#9/HW9.cpp
> +
a lot of empty spaces

2023-12-11 21:07 UTC, sergkonhar commented
@bohdanpc, @helen-black, внёс исправления по комментариям

2023-12-13 18:19 UTC, helen-black commented on HW#9/Functions.cpp
> +	int halfStrLength = std::ceil(fullStrLength / 2.f)-1;
int halfStrLength = fullStrLength / 2;

2023-12-13 19:53 UTC, merged