* added HW15
sergkonhar/Home-works-C-R_D pull request #9
Opened 2023-12-20 23:36 UTC by sergkonhar

@bohdanpc, @helen-black, проверьте пожалуйста домашнее задание #15

2023-12-28 20:03 UTC, bohdanpc requested changes

2023-12-28 20:03 UTC, bohdanpc commented on Home_Work_15/HW15.cpp
> +float avaregeRateOfStudent(Student studentToClaculate)
studentToCalucalte
const Student& , no need to pass the copy just for average calculations

2023-12-28 20:03 UTC, bohdanpc commented on Home_Work_15/HW15.cpp
> +bool sortByAvarageRate(Student firstStudent, Student secondStudent)
const Student&

2023-12-28 20:03 UTC, bohdanpc commented on Home_Work_15/HW15.cpp
> +    float avarageRateFirstStudent = 0;
average

2023-12-28 20:03 UTC, bohdanpc commented on Home_Work_15/HW15.cpp
> +    return bestStudentPtr;
too many steps. Don't even see the need to use additional vector with rates

2024-01-02 18:35 UTC, helen-black requested changes
it's better to separate meaningfull commits with code style refactoring commits

2024-01-02 18:35 UTC, helen-black commented on Home_Work_15/HW15.cpp
> +	avarageRateFirstStudent /= static_cast<float>(std::size(firstStudent.rates));
you can use it:
`float averegeRateOfStudent(const Student& studentToClaculate);`

2024-01-02 18:35 UTC, helen-black commented on Home_Work_15/HW15.cpp
> +		}
you can use it to compare students
`float averegeRateOfStudent(const Student& studentToClaculate);`

2024-01-02 18:35 UTC, helen-black commented on Home_Work_15/HW15.cpp
> +		}
you shouldn't change input array, just save the best student

2024-01-14 10:26 UTC, merged